### ISSUE TITLE
TS2300 & TS2717 when upgraded to 3.4.0

### ISSUE THREAD

**Issue by Scharkee** [MONEI/Shopify-api-node#399]
install: ../../../../../shopify-api-node@3.4.0/node_modules/shopify-api-node/index.d.ts(417,3): error TS2300: Duplicate identifier 'on'.

     install: ../../../../../shopify-api-node@3.4.0/node_modules/shopify-api-node/index.d.ts(417,3): error TS2717: Subsequent property declarations must have the same type.  Property 'on' must be of type '(event: "callLimits", callback: onCallLimitsFn) => Shopify', but here has type '(event: "callGraphqlLimits", callback: onCallGraphqlLimitsFn) => Shopify'.

If this is some sort of conflict on my end, please let me know.

**Comment by lpinca** [comment]
I probably messed up type definitions in https://github.com/MONEI/Shopify-api-node/commit/0e31dfb03fa84fa7169acea406ae1bcf678ced61. Pull request to fix the issue is welcome.
